shadow.shadowtex0.nearest = true
shadow.shadowtex1.nearest = true
blend.gbuffers_water.colortex3=off
blend.gbuffers_terrain.colortex3=off
blend.gbuffers_water.colortex2=off
blend.gbuffers_terrain.colortex2=off

customTexture.endsky = textures/endsky.png